name: Upload PyDID To PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    # TODO Update to latest after dropping Python 3.6 support
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.6
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - name: Confidence check (run tests)
        run: |
          poetry run pytest
      - name: Build package
        run: |
          poetry build
      - name: Publish package
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{secrets.PYPI_API_TOKEN}}
        run: |
          poetry publish
