name: Upload PyDID To PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v2.1.0
    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v2
      with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-3.6-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
          poetry install
    - name: Sanity check (run tests)
      run: |
        poetry run pytest
    - name: Build package
      run: |
          poetry build
    - name: Publish package
      env:
          POETRY_PYPI_TOKEN_PYPI: ${{secrets.PYPI_API_TOKEN}}
      run: |
          poetry publish
