name: Upload PyDID To PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.9
          cache: true
      - name: Install dependencies
        run: pdm install
      - name: Run pytest
        run: pdm run pytest
      - name: Publish
        run: pdm publish
